export const listCarnivalGroups = [
    {
        id: '0',
        title: 'O Python do vovô não sobe mais',
        img: './src/assets/img/cardsImg/card-img-o-python-do-vovo-nao-sobe-mais.jpg',
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.',
        localization: 'São Paulo - SP',
    },
    {
        id:'1',
        title: 'Todo mundo null',
        img: './src/assets/img/cardsImg/card-img-todo-mundo-null.jpg',
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.',
        localization: 'Florianópolis - SC',
    },
    {
        id:'2',
        title: 'Hoje dou exception',
        img: '../src/assets/img/cardsImg/card-img-hoje-dou-exception .jpg',
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.',
        localization: 'Curitiba - PR',
    },
    {
        id:'3',
        title: 'Manda Node',
        img: './src/assets/img/cardsImg/card-ing-manda-node.jpg',
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.',
        localization: 'Salvador - BA',
    },
    {
        id:'4',
        title: 'Só no back-end',
        img: './src/assets/img/cardsImg/card-img-so-no-back-end.jpg',
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.',
        localization: 'São Paulo - SP',
    },
    {
        id:'5',
        title: 'Esse anel não é de Ruby',
        img: './src/assets/img/cardsImg/card-img-esse-anel-nao-e-de-ruby.jpg',
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.',
        localization: 'São Paulo - SP',
    },
    {
        id:'6',
        title: 'Pimenta no C# dos outros é refresco',
        img: './src/assets/img/cardsImg/card-img-primenta-no-c-dos-outros-e-refresco.jpg',
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.',
        localization: 'Rio de Janeiro - RJ',
    },
    {
        id:'7',
        title: 'EnCACHE aqui',
        img: './src/assets/img/cardsImg/card-img-encache-aqui.jpg',
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.',
        localization: 'Porto Alegre - RS',
    },
    {
        id:'8',
        title: 'Não valho nada mas JAVA li',
        img: './src/assets/img/cardsImg/card-ing-nao-valho-nada-mas-java-li.jpg',
        description: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.',
        localization: 'São Paulo - SP',
    },
]